# Generated by Django 2.2.5 on 2019-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('facebook_id', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('nickname', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('household_id', models.TextField(null=True)),
                ('pin', models.TextField(null=True)),
            ],
        ),
    ]
