# Generated by Django 2.2.5 on 2019-10-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(null=True)),
                ('user_id', models.TextField(null=True)),
                ('no_question', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(null=True)),
                ('session_id', models.TextField(null=True)),
                ('user_id', models.TextField(null=True)),
                ('question_id', models.TextField(null=True)),
                ('transcript', models.TextField(null=True)),
                ('bucket_url', models.TextField(null=True)),
                ('time_completion', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='household_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pin',
        ),
    ]
