# Generated by Django 2.2.5 on 2019-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191027_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='facial_emotion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='smile',
            field=models.BooleanField(null=True),
        ),
    ]
