# Generated by Django 2.2.5 on 2019-10-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191027_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answer_keywords',
        ),
        migrations.RenameField(
            model_name='userresponse',
            old_name='keywords',
            new_name='keywords_missed',
        ),
    ]
