# Generated by Django 2.2.5 on 2019-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20191027_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
